server:
  port: 8081
  session:
      timeout: 3600
spring:
  thymeleaf:
    prefix: classpath:/templates/mainPages/
  session:
    store-type: redis
    redis:
      namespace: myLogin
  redis:
      host: 192.168.1.2
      password: 123456